## Based on https://github.com/gosddc/vagrant-vcenter
##

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vcenter'

nodes = []

#In case we want to set up a stack of hosts
#[*1..5].each do |n|
#  nodes << { hostname: "centos#{n}",
#             box: 'gosddc/centos65-x64',
#             ip: "10.250.21.#{n}",
#             mem: 1024 * n,
#             cpu: n }
#end

#The bash script that'll update our machine and install OpsCenter etc.
opsc_script = <<SCRIPT
#!/bin/bash
cat > /etc/hosts <<EOF
127.0.0.1       localhost

172.30.3.254   node0
EOF

# install a few base packages
echo "Updating OS with latest packages, without Kernel updates."
yum update -y --exclude=kernel*,redhat-release* > /dev/null
echo
echo "Installing pre-requisites"
yum install vim curl zip unzip git python-pip -y > /dev/null

# install OpsCenter
cat > /etc/yum.repos.d/datastax.repo <<EOF
[opscenter] 
name = DataStax Repository
baseurl = http://rpm.datastax.com/community
enabled = 1
gpgcheck = 0
EOF

echo "Enabled Datastax repo... refreshing.."
yum update -y --exclude=kernel*,redhat-release* > /dev/null
echo "Installing OpsCenter"
yum install opscenter -y > /dev/null
echo "Starting OpsCenter"
service opscenterd start

echo "     ==== All DONE ! ==="
echo "Vagrant provisioning complete"
SCRIPT

nodes << { hostname: "VagrantTest",
           box: 'gosddc/centos65-x64',
           ip: "172.30.3.254",
           mem: 1024,
           cpu: 1 }

Vagrant.configure('2') do |config|

  # Go through nodes and configure each of them.
  nodes.each do |node|

    config.vm.provider :vcenter do |vcenter|
      vcenter.hostname = 'vcenter server name'
      vcenter.username = 'username'
      vcenter.password = 'password'
      vcenter.folder_name = 'VagrantTest'
      vcenter.datacenter_name = 'QA'
      vcenter.computer_name = 'cluster or vsphere machine name'
      vcenter.datastore_name = 'datastore name'
      vcenter.network_name = 'network name'
      vcenter.linked_clones = true
      vcenter.disable_auto_vm_name = true 
    end

    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = node[:box]
      node_config.vm.hostname = node[:hostname]
 
      # Let's configure the network for the VM, only the ip changes and is
      # coming from the nodes array
      node_config.vm.network :public_network,
                             ip: node[:ip],
                             netmask: '255.255.0.0',
                             gateway: '172.30.0.3',
                             dns_server_list: ['8.8.4.4', '8.8.8.8'],
                             dns_suffix_list: ['lab.netuitive.com']

      # Let's override some provider settings for specific VMs
      node_config.vm.provider :vcenter do |override|
        # Override number of cpu and memory based on what's in the nodes array
        override.num_cpu = node[:cpu]
        override.memory = node[:mem]
        case node[:hostname]
        # Override the folder name based on the hostname of the VM
        when /centos/
          override.folder_name = 'Vagrant/centos'
        when /precise/
          override.folder_name = 'Vagrant/ubuntu/precise'
          override.enable_vm_customization = false
        end
      end
      node_config.nfs.functional = false
    end
    config.vm.provision :shell, :inline => opsc_script
  end
end
