Vagrant.configure("2") do |config|
  ## Choose your base box
  config.vm.box = "chef/centos-6.5"
  config.vm.hostname = "postgres"
  config.vm.network :private_network, ip: "10.211.55.90"

  ## For masterless, mount your file roots file root
  config.vm.synced_folder "salt/roots/", "/srv/"

  ## Set your salt configs here
  config.vm.provision :salt do |salt|

    ## Minion config is set to ``file_client: local`` for masterless
    salt.minion_config = "salt/minion"

    ## Installs our example formula in "salt/roots/salt"
    ## salt.run_highstate = true

  end
end
